config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'about', to: 'about#index'
  get 'users', to: 'users#show_all'
  get 'languages', to: 'languages#show_all'

  resources :users, only: [:show] do
    resources :languages, only: [:show], controller: 'users/languages'
  end

  resources :languages, only: [:show]

  # Routes for showing the search
  resources :users do
    collection do
      get 'show_all' 
    end
  end

  resources :languages do
    collection do
      get 'show_all' 
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :languages
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
        @data_sources = [
          { name: 'Users CSV', description: 'CSV file containing users data.' },
          { name: 'Faker Gem', description: 'Gem used to generate fake data for languages.' }
        ]
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:search].present?
      @users_with_languages = User.includes(:languages).where("users.id LIKE ?", "%#{params[:search]}%")
      @languages = Language.includes(:user).where("languages.name LIKE ?", "%#{params[:search]}%")
    else
      @users_with_languages = User.includes(:languages).all
      @languages = Language.all
    end
  
    @users_with_languages = @users_with_languages.page(params[:page]).per(10)
  end
  
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
    def show_all
      if params[:search].present?
        @languages = Language.where("name LIKE ?", "%#{params[:search]}%").page(params[:page]).per(20)
        if @languages.empty?
          flash.now[:notice] = "Sorry, no results found."
        end
      else
        @languages = Language.page(params[:page]).per(20)
      end
    end
    def show
      @language = Language.find(params[:id])
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show_all
      if params[:search].present?
        @users = User.includes(:laguages).where("title LIKE ?", "%#{params[:search]}%").page(params[:page]).per(10)
        if @users.empty?
          flash.now[:notice] = "Sorry, no results found."
        end
      else
        @users = User.includes(:languages).page(params[:page]).per(10)
      end
    end
    def show
      @user = User.includes(:languages).find(params[:id])
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

<p>In my database, I have two tables namely Users and Languages. Users Tables has five columns namely "id", "location", "age", "created_at", "updated_at". </p>
<p>In languages table have eight columns named "id", "name", "rating", "time_period", "country_spoken", "created_at", "updated_at", "user_id". Users and Languages table have one to many associations between them because one user can know many languages.</p>

<h2>Data Sources</h2>

<ul>
  <% @data_sources.each do |source| %>
    <li><strong><%= source[:name] %>:</strong> <%= source[:description] %></li>
  <% end %>
</ul>

app/views/home/index.html.erb
<h1>Welcome to our family!</h1>

<%= form_tag(root_path, method: "get") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search for Users by Location..." %>
    <%= select_tag :language_id, options_for_select(@languages.map{ |m| [m.name, m.id] }), include_blank: "Select Language" %>
    <%= submit_tag "Search" %>
  <% end %>

<table>
  <thead>
    <tr>
      <th>User Id</th>
      <th>Location</th>
      <th>Languages</th>
    </tr>
  </thead>
  <tbody>
    <% @users_with_languages.each do |user| %>
      <tr>
      <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.location %></td>
        <td>
          <ul>
            <% user.languages.each do |language| %>
              <li><%= language.name %></li>
            <% end %>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users_with_languages %>

app/views/languages/show.html.erb
<h1><%= @language.name %></h1>
<p><strong>Rating:</strong> <%= @language.rating %></p>
<p><strong>Time Period:</strong> <%= @language.time_period %></p>
<p><strong>Country Spoken:</strong> <%= @language.country_spoken %></p>

<p>
  <%= link_to 'Back to Users', user_path(@language.user) %>
</p>

app/views/languages/show_all.html.erb
<h1>Languages all over the World</h1>

<%= form_with(url: languages_path, method: "get") do %>
  <%= text_field_tag(:search, params[:search], placeholder: "Search for Languages") %>
  <%= submit_tag("Search") %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rating</th>
      <th>Time Period</th>
      <th>Country Spoken</th>
    </tr>
  </thead>
  <tbody>
    <% @languages.each do |language| %>
      <tr>
        <td><%= language.name %></td>
        <td><%= language.rating %></td>
        <td><%= language.time_period %></td>
        <td><%= language.country_spoken %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if flash[:notice] %>
  <div class="alert alert-warning">
    <%= flash[:notice] %>
  </div>
<% end %>

<%= paginate @languages %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Language Platform</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <div class="container">
    <header class="py-3 mb-4 border-bottom">
      <div class="container d-flex justify-content-between">
        <h1 class="mb-0">Language Platform</h1>
        <nav>
          <ul class="list-inline">
            <li class="list-inline-item"><%= link_to 'Home', root_path %></li>
            <li class="list-inline-item"><%= link_to 'Users List', users_path %></li>
            <li class="list-inline-item"><%= link_to 'Languages List', languages_path %></li>
            <li class="list-inline-item"><%= link_to 'About', about_path %></li>
          </ul>
        </nav>
      </div>
    </header>

    <main class="mb-4">
      <%= yield %>
    </main>
    
  </div>
</body>
</html>

app/views/users/show.html.erb
<h1><strong>User ID:</strong><%= @user.id %></h1>
<p><strong>Location:</strong> <%= @user.location%></p>
<p><strong>Age:</strong> <%= @user.age %></p>


<h2>Languages Known</h2>
<ul>
  <% @user.languages.each do |language| %>
    <li><%= link_to language.name, language_path(language) %></li>
  <% end %>
</ul>

<%= link_to 'Back to User List', root_path %>

app/views/users/show_all.html.erb
<h1>All Users list</h1>

<%= form_with(url: users_path, method: "get") do %>
  <%= text_field_tag(:search, params[:search], placeholder: "Search for Users by Location") %>
  <%= submit_tag("Search") %>
<% end %>

<table>
  <thead>
    <tr>
      <th>User Id</th>
      <th>Location</th>
      <th>Age</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.location %></td>
        <td><%= user.age %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if flash[:notice] %>
  <div class="alert alert-warning">
    <%= flash[:notice] %>
  </div>
<% end %>

<%= paginate @users %>